Repository jenkinsci/database-plugin, pull requests merged in 2020-08, with the labels that each got.

#10 Update pom + update dependencies + migrate documentation to GitHub
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  LICENSE.md
  README.md
  pom.xml
  src/main/java/org/jenkinsci/plugins/database/AbstractRemoteDatabase.java
  src/main/java/org/jenkinsci/plugins/database/AbstractRemoteDatabaseDescriptor.java
  src/main/java/org/jenkinsci/plugins/database/DatabaseConsole.java
  src/main/java/org/jenkinsci/plugins/database/PerItemDatabaseConfiguration.java
  src/main/java/org/jenkinsci/plugins/database/jpa/PersistenceService.java
  src/main/java/org/jenkinsci/plugins/database/steps/DatabaseConnectionStep.java
  src/main/java/org/jenkinsci/plugins/database/steps/DatabaseContext.java
  src/main/java/org/jenkinsci/plugins/database/steps/SQLStep.java
  src/main/resources/index.jelly
  src/test/java/org/jenkinsci/plugins/database/Main.java
Labels: enhancement

#6 migration to dbcp2
  pom.xml
  src/main/java/org/jenkinsci/plugins/database/BasicDataSource2.java
Labels: enhancement

#14 Remove unused pom config
  pom.xml
Labels: chore

#16 Remove broken example in README
  README.md
Labels: documentation

#15 Update group id for hibernate validator
  pom.xml
Labels: chore
